/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as authAuthRouteImport } from './routes/(auth)/auth'
import { Route as DashboardTradesRouteRouteImport } from './routes/dashboard/trades/route'
import { Route as DashboardEventsRouteRouteImport } from './routes/dashboard/events/route'
import { Route as DashboardWhalesIndexRouteImport } from './routes/dashboard/whales/index'
import { Route as DashboardTradesIndexRouteImport } from './routes/dashboard/trades/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardPricingIndexRouteImport } from './routes/dashboard/pricing/index'
import { Route as DashboardPortfolioIndexRouteImport } from './routes/dashboard/portfolio/index'
import { Route as DashboardPerformanceIndexRouteImport } from './routes/dashboard/performance/index'
import { Route as DashboardCheckoutIndexRouteImport } from './routes/dashboard/checkout/index'
import { Route as DashboardAlertsIndexRouteImport } from './routes/dashboard/alerts/index'
import { Route as DashboardEventsEventIdRouteImport } from './routes/dashboard/events/$eventId'
import { Route as ApiAutumnSplatRouteImport } from './routes/api/autumn.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as DashboardTradesSignalIdIndexRouteImport } from './routes/dashboard/trades/$signalId/index'
import { Route as DashboardCheckoutSuccessIndexRouteImport } from './routes/dashboard/checkout/success/index'

const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => authRouteRoute,
} as any)
const DashboardTradesRouteRoute = DashboardTradesRouteRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsRouteRoute = DashboardEventsRouteRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWhalesIndexRoute = DashboardWhalesIndexRouteImport.update({
  id: '/whales/',
  path: '/whales/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTradesIndexRoute = DashboardTradesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTradesRouteRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPricingIndexRoute = DashboardPricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPortfolioIndexRoute = DashboardPortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPerformanceIndexRoute =
  DashboardPerformanceIndexRouteImport.update({
    id: '/performance/',
    path: '/performance/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCheckoutIndexRoute = DashboardCheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAlertsIndexRoute = DashboardAlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsEventIdRoute = DashboardEventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => DashboardEventsRouteRoute,
} as any)
const ApiAutumnSplatRoute = ApiAutumnSplatRouteImport.update({
  id: '/api/autumn/$',
  path: '/api/autumn/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTradesSignalIdIndexRoute =
  DashboardTradesSignalIdIndexRouteImport.update({
    id: '/$signalId/',
    path: '/$signalId/',
    getParentRoute: () => DashboardTradesRouteRoute,
  } as any)
const DashboardCheckoutSuccessIndexRoute =
  DashboardCheckoutSuccessIndexRouteImport.update({
    id: '/checkout/success/',
    path: '/checkout/success/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/performance': typeof PerformanceRoute
  '/dashboard/events': typeof DashboardEventsRouteRouteWithChildren
  '/dashboard/trades': typeof DashboardTradesRouteRouteWithChildren
  '/auth': typeof authAuthRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/autumn/$': typeof ApiAutumnSplatRoute
  '/dashboard/events/$eventId': typeof DashboardEventsEventIdRoute
  '/dashboard/alerts': typeof DashboardAlertsIndexRoute
  '/dashboard/checkout': typeof DashboardCheckoutIndexRoute
  '/dashboard/performance': typeof DashboardPerformanceIndexRoute
  '/dashboard/portfolio': typeof DashboardPortfolioIndexRoute
  '/dashboard/pricing': typeof DashboardPricingIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/trades/': typeof DashboardTradesIndexRoute
  '/dashboard/whales': typeof DashboardWhalesIndexRoute
  '/dashboard/checkout/success': typeof DashboardCheckoutSuccessIndexRoute
  '/dashboard/trades/$signalId': typeof DashboardTradesSignalIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/performance': typeof PerformanceRoute
  '/dashboard/events': typeof DashboardEventsRouteRouteWithChildren
  '/auth': typeof authAuthRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/autumn/$': typeof ApiAutumnSplatRoute
  '/dashboard/events/$eventId': typeof DashboardEventsEventIdRoute
  '/dashboard/alerts': typeof DashboardAlertsIndexRoute
  '/dashboard/checkout': typeof DashboardCheckoutIndexRoute
  '/dashboard/performance': typeof DashboardPerformanceIndexRoute
  '/dashboard/portfolio': typeof DashboardPortfolioIndexRoute
  '/dashboard/pricing': typeof DashboardPricingIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/trades': typeof DashboardTradesIndexRoute
  '/dashboard/whales': typeof DashboardWhalesIndexRoute
  '/dashboard/checkout/success': typeof DashboardCheckoutSuccessIndexRoute
  '/dashboard/trades/$signalId': typeof DashboardTradesSignalIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/performance': typeof PerformanceRoute
  '/dashboard/events': typeof DashboardEventsRouteRouteWithChildren
  '/dashboard/trades': typeof DashboardTradesRouteRouteWithChildren
  '/(auth)/auth': typeof authAuthRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/autumn/$': typeof ApiAutumnSplatRoute
  '/dashboard/events/$eventId': typeof DashboardEventsEventIdRoute
  '/dashboard/alerts/': typeof DashboardAlertsIndexRoute
  '/dashboard/checkout/': typeof DashboardCheckoutIndexRoute
  '/dashboard/performance/': typeof DashboardPerformanceIndexRoute
  '/dashboard/portfolio/': typeof DashboardPortfolioIndexRoute
  '/dashboard/pricing/': typeof DashboardPricingIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/trades/': typeof DashboardTradesIndexRoute
  '/dashboard/whales/': typeof DashboardWhalesIndexRoute
  '/dashboard/checkout/success/': typeof DashboardCheckoutSuccessIndexRoute
  '/dashboard/trades/$signalId/': typeof DashboardTradesSignalIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/performance'
    | '/dashboard/events'
    | '/dashboard/trades'
    | '/auth'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/autumn/$'
    | '/dashboard/events/$eventId'
    | '/dashboard/alerts'
    | '/dashboard/checkout'
    | '/dashboard/performance'
    | '/dashboard/portfolio'
    | '/dashboard/pricing'
    | '/dashboard/settings'
    | '/dashboard/trades/'
    | '/dashboard/whales'
    | '/dashboard/checkout/success'
    | '/dashboard/trades/$signalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/performance'
    | '/dashboard/events'
    | '/auth'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/autumn/$'
    | '/dashboard/events/$eventId'
    | '/dashboard/alerts'
    | '/dashboard/checkout'
    | '/dashboard/performance'
    | '/dashboard/portfolio'
    | '/dashboard/pricing'
    | '/dashboard/settings'
    | '/dashboard/trades'
    | '/dashboard/whales'
    | '/dashboard/checkout/success'
    | '/dashboard/trades/$signalId'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/dashboard'
    | '/performance'
    | '/dashboard/events'
    | '/dashboard/trades'
    | '/(auth)/auth'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/autumn/$'
    | '/dashboard/events/$eventId'
    | '/dashboard/alerts/'
    | '/dashboard/checkout/'
    | '/dashboard/performance/'
    | '/dashboard/portfolio/'
    | '/dashboard/pricing/'
    | '/dashboard/settings/'
    | '/dashboard/trades/'
    | '/dashboard/whales/'
    | '/dashboard/checkout/success/'
    | '/dashboard/trades/$signalId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  PerformanceRoute: typeof PerformanceRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAutumnSplatRoute: typeof ApiAutumnSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(auth)/auth': {
      id: '/(auth)/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/dashboard/trades': {
      id: '/dashboard/trades'
      path: '/trades'
      fullPath: '/dashboard/trades'
      preLoaderRoute: typeof DashboardTradesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events': {
      id: '/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardEventsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/whales/': {
      id: '/dashboard/whales/'
      path: '/whales'
      fullPath: '/dashboard/whales'
      preLoaderRoute: typeof DashboardWhalesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/trades/': {
      id: '/dashboard/trades/'
      path: '/'
      fullPath: '/dashboard/trades/'
      preLoaderRoute: typeof DashboardTradesIndexRouteImport
      parentRoute: typeof DashboardTradesRouteRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/pricing/': {
      id: '/dashboard/pricing/'
      path: '/pricing'
      fullPath: '/dashboard/pricing'
      preLoaderRoute: typeof DashboardPricingIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/portfolio/': {
      id: '/dashboard/portfolio/'
      path: '/portfolio'
      fullPath: '/dashboard/portfolio'
      preLoaderRoute: typeof DashboardPortfolioIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/performance/': {
      id: '/dashboard/performance/'
      path: '/performance'
      fullPath: '/dashboard/performance'
      preLoaderRoute: typeof DashboardPerformanceIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/checkout/': {
      id: '/dashboard/checkout/'
      path: '/checkout'
      fullPath: '/dashboard/checkout'
      preLoaderRoute: typeof DashboardCheckoutIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/alerts/': {
      id: '/dashboard/alerts/'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof DashboardAlertsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events/$eventId': {
      id: '/dashboard/events/$eventId'
      path: '/$eventId'
      fullPath: '/dashboard/events/$eventId'
      preLoaderRoute: typeof DashboardEventsEventIdRouteImport
      parentRoute: typeof DashboardEventsRouteRoute
    }
    '/api/autumn/$': {
      id: '/api/autumn/$'
      path: '/api/autumn/$'
      fullPath: '/api/autumn/$'
      preLoaderRoute: typeof ApiAutumnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/trades/$signalId/': {
      id: '/dashboard/trades/$signalId/'
      path: '/$signalId'
      fullPath: '/dashboard/trades/$signalId'
      preLoaderRoute: typeof DashboardTradesSignalIdIndexRouteImport
      parentRoute: typeof DashboardTradesRouteRoute
    }
    '/dashboard/checkout/success/': {
      id: '/dashboard/checkout/success/'
      path: '/checkout/success'
      fullPath: '/dashboard/checkout/success'
      preLoaderRoute: typeof DashboardCheckoutSuccessIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authAuthRoute: typeof authAuthRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authAuthRoute: authAuthRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface DashboardEventsRouteRouteChildren {
  DashboardEventsEventIdRoute: typeof DashboardEventsEventIdRoute
}

const DashboardEventsRouteRouteChildren: DashboardEventsRouteRouteChildren = {
  DashboardEventsEventIdRoute: DashboardEventsEventIdRoute,
}

const DashboardEventsRouteRouteWithChildren =
  DashboardEventsRouteRoute._addFileChildren(DashboardEventsRouteRouteChildren)

interface DashboardTradesRouteRouteChildren {
  DashboardTradesIndexRoute: typeof DashboardTradesIndexRoute
  DashboardTradesSignalIdIndexRoute: typeof DashboardTradesSignalIdIndexRoute
}

const DashboardTradesRouteRouteChildren: DashboardTradesRouteRouteChildren = {
  DashboardTradesIndexRoute: DashboardTradesIndexRoute,
  DashboardTradesSignalIdIndexRoute: DashboardTradesSignalIdIndexRoute,
}

const DashboardTradesRouteRouteWithChildren =
  DashboardTradesRouteRoute._addFileChildren(DashboardTradesRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardEventsRouteRoute: typeof DashboardEventsRouteRouteWithChildren
  DashboardTradesRouteRoute: typeof DashboardTradesRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAlertsIndexRoute: typeof DashboardAlertsIndexRoute
  DashboardCheckoutIndexRoute: typeof DashboardCheckoutIndexRoute
  DashboardPerformanceIndexRoute: typeof DashboardPerformanceIndexRoute
  DashboardPortfolioIndexRoute: typeof DashboardPortfolioIndexRoute
  DashboardPricingIndexRoute: typeof DashboardPricingIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardWhalesIndexRoute: typeof DashboardWhalesIndexRoute
  DashboardCheckoutSuccessIndexRoute: typeof DashboardCheckoutSuccessIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardEventsRouteRoute: DashboardEventsRouteRouteWithChildren,
  DashboardTradesRouteRoute: DashboardTradesRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAlertsIndexRoute: DashboardAlertsIndexRoute,
  DashboardCheckoutIndexRoute: DashboardCheckoutIndexRoute,
  DashboardPerformanceIndexRoute: DashboardPerformanceIndexRoute,
  DashboardPortfolioIndexRoute: DashboardPortfolioIndexRoute,
  DashboardPricingIndexRoute: DashboardPricingIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardWhalesIndexRoute: DashboardWhalesIndexRoute,
  DashboardCheckoutSuccessIndexRoute: DashboardCheckoutSuccessIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  PerformanceRoute: PerformanceRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAutumnSplatRoute: ApiAutumnSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
