export const CONFIG = {
  MIN_TRADE_SIZE_USD: 500,
  IGNORE_PRICE_LOW: 0.02,
  IGNORE_PRICE_HIGH: 0.98,
  NEW_MARKETS_FOR_ANALYSIS: 3,
  MARKETS_TO_ANALYZE: 3,
  ANALYSIS_CHECK_INTERVAL_SECONDS: 300,
  TOP_MARKETS_COUNT: 5,
  USE_SWARM_MODE: true,
  SEND_PRICE_INFO_TO_AI: false,
  DATA_FOLDER: "./data/polymarket",
  WEBSOCKET_URL: "wss://ws-live-data.polymarket.com",
} as const;

export const IGNORE_CRYPTO_KEYWORDS = [
  "bitcoin",
  "btc",
  "ethereum",
  "eth",
  "crypto",
  "solana",
  "sol",
  "dogecoin",
  "doge",
  "shiba",
  "cardano",
  "ada",
  "ripple",
  "xrp",
] as const;

export const IGNORE_SPORTS_KEYWORDS = [
  "nba",
  "nfl",
  "mlb",
  "nhl",
  "mls",
  "ufc",
  "boxing",
  "football",
  "basketball",
  "baseball",
  "hockey",
  "soccer",
  "super bowl",
  "world series",
  "playoffs",
  "championship",
  "lakers",
  "warriors",
  "celtics",
  "knicks",
  "heat",
  "bucks",
  "cowboys",
  "patriots",
  "chiefs",
  "eagles",
  "packers",
  "yankees",
  "dodgers",
  "red sox",
  "mets",
  "premier league",
  "la liga",
  "champions league",
  "tennis",
  "golf",
  "nascar",
  "formula 1",
  "f1",
  "cricket",
] as const;
